name: PNPM install
description: Run pnpm install with cache enabled

inputs:
  enable-corepack:
    description: Enable corepack
    required: false
    default: 'true'
  node-version:
    description: Node version to use
    required: false
    default: '24'

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      env:
        HUSKY: '0' # By default do not run HUSKY install
        SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1 # By default do not run simple-git-hooks install
