name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-cli:
    name: Build CLI
    uses: ./.github/workflows/build-cli.yml
  integration-testing:
    name: Integration Testing
    needs: build-cli
    uses: ./.github/workflows/integration-testing.yml
