name: Unit Testing

on: workflow_call

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ matrix.version }}
      - name: Run Vitest
        run: pnpm run test:unit
